CREATE TABLE [HTS_CODE_A] (
  [HTS_CD1] varchar(2),
  [Pr_Def] varchar(1500),
  [Custom_Def] varchar(1500),
  [CC_3166A3] varchar(3),
  PRIMARY KEY ([HTS_CD1])
);


CREATE TABLE [HTS_CODE_B] (
  [HTS_CD1] varchar(2),
  [HTS_CD2] varchar(2),
  [Pr_Def] varchar(1500),
  [Custom_Def] varchar(1500),
  [CC_3166A3] varchar(3),
  PRIMARY KEY ([HTS_CD1], [HTS_CD2]),
  constraint FK_HTS_CODE_B_HTS_CODE_A Foreign Key ([HTS_CD1]) References HTS_CODE_A ([HTS_CD1])
);


CREATE TABLE [HTS_CODE_C] (
  [HTS_CD1] varchar(2),
  [HTS_CD2] varchar(2),
  [HTS_CD3] varchar(4),
  [Pr_Def] varchar(1500),
  [Custom_Def] varchar(1500),
  [CC_3166A3] varchar(3),
  PRIMARY KEY ([HTS_CD1], [HTS_CD2], [HTS_CD3]),
  constraint FK_HTS_CODE_C_HTS_CODE_B Foreign Key ([HTS_CD1], [HTS_CD2]) References HTS_CODE_B ([HTS_CD1], [HTS_CD2])
);


CREATE TABLE [HTS_CODE_D] (
  [HTS_CD1] varchar(2),
  [HTS_CD2] varchar(2),
  [HTS_CD3] varchar(4),
  [HTS_CD4] varchar(4),
  [Pr_Def] varchar(1500),
  [Custom_Def] varchar(1500),
  [CC_3166A3] varchar(3),
  PRIMARY KEY ([HTS_CD1], [HTS_CD2], [HTS_CD3], [HTS_CD4]),
  constraint FK_HTS_CODE_D_HTS_CODE_C Foreign Key ([HTS_CD1], [HTS_CD2], [HTS_CD3]) References HTS_CODE_C ([HTS_CD1], [HTS_CD2], [HTS_CD3])
);

CREATE TABLE [HTS_CODE_E] (
  [HTS_CD1] varchar(2),
  [HTS_CD2] varchar(2),
  [HTS_CD3] varchar(4),
  [HTS_CD4] varchar(4),
  [HTS_CD5] varchar(4),
  [Pr_Def] varchar(1500),
  [Custom_Def] varchar(1500),
  [CC_3166A3] varchar(3),
  PRIMARY KEY ([HTS_CD1], [HTS_CD2], [HTS_CD3], [HTS_CD4], [HTS_CD5]),
  constraint FK_HTS_CODE_E_HTS_CODE_D Foreign Key ([HTS_CD1], [HTS_CD2], [HTS_CD3], [HTS_CD4]) References HTS_CODE_D ([HTS_CD1], [HTS_CD2], [HTS_CD3], [HTS_CD4])
);



CREATE TABLE [Employee] (
  [Emp_ID] varchar(10),
  [Emp_Email] varchar(40),
  [First_Name] varchar(16),
  [Middle_Name] varchar(16),
  [Last_Name] varchar(16),
  [Ph_Num] varchar(16),
  [Cell_Num] varchar(16),
  [Supv_ID] varchar(10),
  [Supv_Email] varchar(40),
  [ImgLink] varchar(400),
  PRIMARY KEY ([Emp_ID])
);


CREATE TABLE [Item] (
  [Item_ID] varchar(25),
  [Item_Name] varchar(100),
  [Item_Desc] varchar(300),
  [ImgLink] varchar(400),
  PRIMARY KEY ([Item_ID])
);



CREATE TABLE [ITEM_HTSC_AUDIT] (
  [Emp_ID] varchar(10),
  [Item_ID] varchar(25),
  [Cnt] int,
  [HTSC] varchar(15),
  [Last_upd_dtm] DateTime,
  [Reason] varchar(500),
  PRIMARY KEY ([Emp_ID], [Item_ID], [Cnt]),
  constraint FK_ITEM_HTSC_AUDIT_Employee Foreign Key ([Emp_ID]) References Employee ([Emp_ID]),
  constraint FK_ITEM_HTSC_AUDIT_Item Foreign Key ([Item_ID]) References Item ([Item_ID])
);

CREATE TABLE [ITEM_HTSC] (
  [Emp_ID] varchar(10),
  [Item_ID] varchar(25),
  [HTSC] varchar(14),
  [Last_upd_dtm] DateTime,
  [CC_3166A3] varchar(3),
  PRIMARY KEY ([Emp_ID], [Item_ID]),
  constraint FK_ITEM_HTSC_Employee Foreign Key ([Emp_ID]) References Employee ([Emp_ID]),
  constraint FK_ITEM_HTSC_Item Foreign Key ([Item_ID]) References Item ([Item_ID])
);

CREATE TABLE [HTS_CODE_DUMP] (
  [HTS_CD_SEQ] int,
  [HTS_CD1] varchar(2),
  [HTS_CD2] varchar(2),
  [HTS_CD3] varchar(6),
  [HTS_CD4] varchar(6),
  [HTS_CD5] varchar(6),
  [HTS_CD6] varchar(6),
  [HTS_CD7] varchar(6),
  [HTS_CD8] varchar(6),
  [HTS_CD9] varchar(6),
  [HTS_CD10] varchar(6),
  [Pr_Def] varchar(1500),
  [Custom_Def] varchar(1500),
  [CC_3166A3] varchar(3),
  UNIQUE ([HTS_CD_SEQ], [HTS_CD1], [HTS_CD2], [HTS_CD3], [HTS_CD4], [HTS_CD5],[HTS_CD6], [HTS_CD7], [HTS_CD8], [HTS_CD9], [HTS_CD10])
);

CREATE INDEX [UK] ON  [HTS_CODE_DUMP] ([HTS_CD_SEQ], [HTS_CD1], [HTS_CD2], [HTS_CD3], [HTS_CD4], [HTS_CD5],[HTS_CD6], [HTS_CD7], [HTS_CD8], [HTS_CD9], [HTS_CD10]);

create table [USER_ACCESS]
(
  [Emp_ID] varchar(10),
  [Pwd] varchar(20),

  PRIMARY KEY ([Emp_ID]),
  constraint FK_USER_ACCESS_Employee Foreign Key ([Emp_ID]) References Employee ([Emp_ID])

);


create Table [CONFIG](

  [CODE_ID] varchar(10),
  [CODE_DESC] varchar(400),
  PRIMARY KEY ([CODE_ID])

);





###Insert Statements

INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('1', '85', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ELECTRICAL MACHINERY AND EQUIPMENT AND PARTS THEREOF; SOUND RECORDERS AND REPRODUCERS, TELEVISION IMAGE AND SOUND RECORDERS AND REPRODUCERS, AND PARTS AND ACCESSORIES OF SUCH ARTICLES', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('2', '85', '36', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Electrical apparatus for switching or protecting electrical circuits, or for making connections to or in electrical circuits (for example, switches, relays, fuses, surge suppressors, plugs, sockets, lamp-holders and other connectors, junction boxes), for a voltage not exceeding 1,000 V; connectors for optical fibers, optical fiber bundles or cables:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '36', '1000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Fuses', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '1000', '20', NULL, NULL, NULL, NULL, NULL, NULL, 'Glass cartridge', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '1000', '40', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '36', '2000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Automatic Circuit Breakers', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '2000', '20', NULL, NULL, NULL, NULL, NULL, NULL, 'Molded Case', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '2000', '40', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '36', '30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Other apparatus for protecting electrical circuits:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '30', '4000', NULL, NULL, NULL, NULL, NULL, NULL, 'Motor overload protectors', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '30', '8000', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '36', 'X1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Relays', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', 'X1', '4100', NULL, NULL, NULL, NULL, NULL, NULL, 'For a voltage not exceeding 60 V.', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', 'X1', '4100', '05', NULL, NULL, NULL, NULL, NULL, 'Automotive signaling flashers', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', 'X1', '4100', 'X1', NULL, NULL, NULL, NULL, NULL, 'With contacts rated at less than 10 A:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X1', '4100', 'X1', '20', NULL, NULL, NULL, NULL, 'Electromechanical', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X1', '4100', 'X1', '30', NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', 'X1', '4100', 'X2', NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X1', '4100', 'X2', '45', NULL, NULL, NULL, NULL, 'Contactors', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X1', '4100', 'X2', '50', NULL, NULL, NULL, NULL, 'Electromechanical', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X1', '4100', 'X2', '60', NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', 'X1', '4900', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', 'X1', '4900', 'X1', NULL, NULL, NULL, NULL, NULL, 'With contacts rated at less than 10 A:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X1', '4900', 'X1', '50', NULL, NULL, NULL, NULL, 'Electromechanical', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X1', '4900', 'X1', '55', NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', 'X1', '4900', 'X2', NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X1', '4900', 'X2', '65', NULL, NULL, NULL, NULL, 'Contactors', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X1', '4900', 'X2', '75', NULL, NULL, NULL, NULL, 'Electromechanical', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X1', '4900', 'X2', '80', NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '36', '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Other Switches', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '50', '4000', NULL, NULL, NULL, NULL, NULL, NULL, 'Motor starters', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '50', '7000', NULL, NULL, NULL, NULL, NULL, NULL, 'Electronic AC switches consisting of optically
coupled input and output circuits (insulated thyristor AC switches); electronic switches, including temperature protected switches, consisting of a transistor and a logic chip (chip-on-chip technology); electromechanical snap-action switches for a current not exceeding 11 amps', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '50', '90', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', '50', '90', 'X1', NULL, NULL, NULL, NULL, NULL, 'Rotary', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', '50', '90', 'X1', '20', NULL, NULL, NULL, NULL, 'Rated at not over 5 A', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', '50', '90', 'X1', '25', NULL, NULL, NULL, NULL, 'Rated at over 5 A', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', '50', '90', 'X2', NULL, NULL, NULL, NULL, NULL, 'Push-button', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', '50', '90', 'X2', '35', NULL, NULL, NULL, NULL, 'Rated at over 5 A', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', '50', '90', 'X2', 'X1', NULL, NULL, NULL, NULL, 'Rated at not over 5 A', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('7', '85', '36', '50', '90', 'X2', 'X1', '31', NULL, NULL, NULL, 'Momentary contact', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('7', '85', '36', '50', '90', 'X2', 'X1', '32', NULL, NULL, NULL, 'Other, gang switches', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('7', '85', '36', '50', '90', 'X2', 'X1', '33', NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', '50', '90', '40', NULL, NULL, NULL, NULL, NULL, 'Snap-action, other than limit', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', '50', '90', '45', NULL, NULL, NULL, NULL, NULL, 'Knife', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', '50', '90', '50', NULL, NULL, NULL, NULL, NULL, 'Slide', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', '50', '90', '55', NULL, NULL, NULL, NULL, NULL, 'Limit', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', '50', '90', '55', NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '36', 'X2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Lamp-holders, plugs and sockets:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', 'X2', '610000', NULL, NULL, NULL, NULL, NULL, NULL, 'Lamp-holders', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', 'X2', '69', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', 'X2', '69', '8000', NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', 'X2', '69', '40', NULL, NULL, NULL, NULL, NULL, 'Coaxial connectors; cylindrical multicontact connectors; rack and panel connectors; printed circuit connectors; ribbon or flat cable connectors ', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X2', '69', '40', '10', NULL, NULL, NULL, NULL, 'Coaxial connectors', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X2', '69', '40', '20', NULL, NULL, NULL, NULL, 'Cylindrical multicontact connectors', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X2', '69', '40', '30', NULL, NULL, NULL, NULL, 'Rack and panel connectors', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X2', '69', '40', '40', NULL, NULL, NULL, NULL, 'Printed circuit connectors', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '36', 'X2', '69', '40', '51', NULL, NULL, NULL, NULL, 'Ribbon or flat cable connectors', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '36', '700000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Connectors for optical fibers, optical fiber bundles or cables', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '36', '90', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Other apparatus', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '90', '4000', NULL, NULL, NULL, NULL, NULL, NULL, 'Terminals, electrical splices and electrical couplings; wafer probers', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '90', '6000', NULL, NULL, NULL, NULL, NULL, NULL, 'Battery clamps of a kind used in motor vehicles of heading 8702, 8703, 8704 or 8711', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '36', '90', '85', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', '90', '85', '10', NULL, NULL, NULL, NULL, NULL, 'Electrical distribution ducts', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', '90', '85', '30', NULL, NULL, NULL, NULL, NULL, 'Junction boxes', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '36', '90', '85', '85', NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('2', '85', '37', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Boards, panels, consoles, desks, cabinets and other bases, equipped with two or more apparatus of heading 8535 or 8536, for electric control or the distribution of electricity, including those incorporating instruments or apparatus of chapter 90, and numerical control apparatus, other than switching apparatus of heading 8517', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '37', '10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'For a voltage not exceeding 1,000 V:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '37', '10', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Assembled with outer housing or supprts, for the goods of headings 8421, 8422, 8450 or 8516', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '37', '10', '6000', NULL, NULL, NULL, NULL, NULL, NULL, 'Motor Control centers', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '37', '10', 'X1', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '37', '10', 'X1', '8000', NULL, NULL, NULL, NULL, NULL, 'Touch-sensitive data input devices (so-called "touch screens") without display capabilities, for incorporation into apparatus having a display, which function by detecting the presence and location of a touch within the display area (such sensing may be obtained by means of resistance, electrostatic capacity, acoustic pulse recognition, infra-red lights or other touch-sensitive technology)', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '37', '10', 'X1', '91', NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '37', '10', 'X1', '91', '20', NULL, NULL, NULL, NULL, 'Switchgear assemblies and switchboards', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '37', '10', 'X1', '91', '30', NULL, NULL, NULL, NULL, 'Numerical controls for controlling machine tools', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '37', '10', 'X1', '91', 'X1', NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('7', '85', '37', '10', 'X1', '91', 'X1', '50', NULL, NULL, NULL, 'Panel boards and distribution boards', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('7', '85', '37', '10', 'X1', '91', 'X1', '60', NULL, NULL, NULL, 'Programmable controllers', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('7', '85', '37', '10', 'X1', '91', 'X1', '70', NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '37', '2000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'For a voltage exceeding 1,000 V:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '37', '2000', '20', NULL, NULL, NULL, NULL, NULL, NULL, 'Switchgear assemblies and switchboards', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '37', '2000', '40', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('2', '85', '38', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Parts suitable for use solely or principally with the apparatus of heading 8535, 8536 or 8537:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '38', '100000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Boards, panels, consoles, desks, cabinets and other bases for the goods of heading 8537, not equipped with their apparatus', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '85', '38', '90', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '38', '90', 'X1', NULL, NULL, NULL, NULL, NULL, NULL, 'Printed circuit assemblies', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '38', '90', 'X1', '1000', NULL, NULL, NULL, NULL, NULL, 'Of an article of heading 8537 for one of the articles described in additional U.S. note 11 to chapter 85', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '38', '90', 'X1', '3000', NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '38', '90', '4000', NULL, NULL, NULL, NULL, NULL, NULL, 'Other, for the articles of subheading 8535.90.40, 8536.30.40 or 8536.50.40, of ceramic or metallic materials, electrically or mechanically reactive to changes in temperature', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '85', '38', '90', 'X2', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '38', '90', 'X2', '6000', NULL, NULL, NULL, NULL, NULL, 'Molded Parts', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '85', '38', '90', 'X2', '81', NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '38', '90', 'X2', '81', '20', NULL, NULL, NULL, NULL, 'Of automatic circuit breakers', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('6', '85', '38', '90', 'X2', '81', 'X1', NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('7', '85', '38', '90', 'X2', '81', 'X1', '40', NULL, NULL, NULL, 'Metal contacts', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('7', '85', '38', '90', 'X2', '81', 'X1', '60', NULL, NULL, NULL, 'Other parts of switchgear, switchboards, panel boards and distribution boards', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('7', '85', '38', '90', 'X2', '81', 'X1', '80', NULL, NULL, NULL, 'Other', NULL, NULL);


INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('1', '61', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ARTICLES OF APPAREL AND CLOTHING ACCESSORIES, KNITTED OR CROCHETED', NULL, NULL);

INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('2', '61', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Mens or boys overcoats, carcoats, capes, cloaks, anoraks (including ski-jackets), windbreakers and similar articles, knitted or crocheted, other than those of heading 6103', NULL, NULL);

INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('2', '61', '02', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Womens or girls overcoats, carcoats, capes, cloaks, anoraks (including ski-jackets), windbreakers and similar articles, knitted or crocheted, other than those of heading 6104', NULL, NULL);

INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('2', '61', '03', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Mens or boys suits, ensembles, suit-type jackets, blazers, trousers, bib and brace overalls, breeches and shorts (other than swimwear), knitted or crocheted:', NULL, NULL);

INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '61', '01', '2000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Of cotton', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '01', '2000', '10', NULL, NULL, NULL, NULL, NULL, NULL, 'Mens', NULL, NULL);

INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '01', '2000', '20', NULL, NULL, NULL, NULL, NULL, NULL, 'Boys', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '61', '01', '30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Of man-made fibers:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '01', '30', '1000', NULL, NULL, NULL, NULL, NULL, NULL, 'Containing 25 percent or more by weight of leather', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '01', '30', '1500', NULL, NULL, NULL, NULL, NULL, NULL, 'Containing 23 percent or more by weight of wool or fine animal hair', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '01', '30', '20', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '01', '30', '20', '10', NULL, NULL, NULL, NULL, NULL, 'Mens', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '01', '30', '20', '20', NULL, NULL, NULL, NULL, NULL, 'Boys', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '61', '01', '90', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Of other textile materials:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '01', '90', '0500', NULL, NULL, NULL, NULL, NULL, NULL, 'Of wool or fine animal hair', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '01', '90', '1000', NULL, NULL, NULL, NULL, NULL, NULL, 'Containing 70 percent or more by weight of silk or silk waste', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '01', '90', '90', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '01', '90', '90', '10', NULL, NULL, NULL, NULL, NULL, 'Subject to cotton restraints', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '01', '90', '90', '20', NULL, NULL, NULL, NULL, NULL, 'Subject to wool restraints', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '01', '90', '90', '30', NULL, NULL, NULL, NULL, NULL, 'Subject to man-made fiber restraints', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '01', '90', '90', '60', NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);


INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '61', '02', '100000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Of wool or fine animal hair', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '61', '02', '2000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Of cotton', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '02', '2000', '10', NULL, NULL, NULL, NULL, NULL, NULL, 'Womens', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '02', '2000', '20', NULL, NULL, NULL, NULL, NULL, NULL, 'Girls', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '61', '02', '30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Of man-made fibers:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '02', '30', '0500', NULL, NULL, NULL, NULL, NULL, NULL, 'Containing 25 percent or more by weight of leather', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '02', '30', '1000', NULL, NULL, NULL, NULL, NULL, NULL, 'Containing 23 percent or more by weight of wool or fine animal hair', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '02', '30', '20', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '02', '30', '20', '10', NULL, NULL, NULL, NULL, NULL, 'Womens', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '02', '30', '20', '20', NULL, NULL, NULL, NULL, NULL, 'Girls', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('3', '61', '02', '90', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Of other textile materials:', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '02', '90', '1000', NULL, NULL, NULL, NULL, NULL, NULL, 'Containing 70 percent or more by weight of silk or silk waste', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('4', '61', '02', '90', '90', NULL, NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '02', '90', '90', '05', NULL, NULL, NULL, NULL, NULL, 'Subject to cotton restraints', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '02', '90', '90', '10', NULL, NULL, NULL, NULL, NULL, 'Subject to wool restraints', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '02', '90', '90', '15', NULL, NULL, NULL, NULL, NULL, 'Subject to man-made fiber restraints', NULL, NULL);
INSERT INTO HTS_CODE_DUMP (HTS_CD_SEQ, HTS_CD1, HTS_CD2, HTS_CD3, HTS_CD4, HTS_CD5, HTS_CD6, HTS_CD7, HTS_CD8, HTS_CD9, HTS_CD10, Pr_Def, Custom_Def, CC_3166A3) VALUES ('5', '61', '02', '90', '90', '30', NULL, NULL, NULL, NULL, NULL, 'Other', NULL, NULL);


insert into [USER_ACCESS] values('0002', 'UIC')

INSERT INTO [CONFIG] ([CODE_ID], [CODE_DESC]) VALUES ('ID_001', 'Please select the option from below that fits your product.');
INSERT INTO [CONFIG] ([CODE_ID], [CODE_DESC]) VALUES ('ID_002', 'Please select/click this option if the definition fits the item you are classifying');
INSERT INTO [CONFIG] ([CODE_ID], [CODE_DESC]) VALUES ('ID_003', 'Incomplete Code');
INSERT INTO [CONFIG] ([CODE_ID], [CODE_DESC]) VALUES ('ID_004', 'Complete Code - Please click on the Email button to send an email to Seymour, Bethany (Bethany.Seymour@regalrexnord.com) with the Complete code and an image of the product.');


